export default {
  vi: {
    domain: 'cuahangsansale.ff.garena.vn',
    logoSite: '/images/logo.png',
    saleTag: 'Sale',
    refreshSale: 'Làm mới giảm giá',
    buyText: 'Mua',
    boughtText: 'Đã mua',
    cantBuyText: 'Không thể mua',
    guideText: 'Guide text...',
    ticketLabel: 'vé giảm giá',
    confirmBuy: `Bạn chắc chắn muốn mua gói vật phẩm này?<br>Chọn vé giảm giá bạn mong muốn`,
    warning: 'Bạn chưa chọn vé giảm giá<br>bạn có muốn tiếp tục mua vật phẩm không?',
    rerollConfirm: 'Sử dụng [xxx] <img src="/images/icon-diamond.png" class="icon-diamond" alt=""/> để làm mới giảm giá?',
    purchasedError: 'Bạn đã sử dụng vé giảm giá rồi',
    rerollSuccess: 'Làm mới giảm giá thành công!',
    ruleTitle: 'Thể lệ',
    rule: '<p>Lorem</p>',
    historyTitle: 'Lịch sử',
    timeField: 'Thời gian',
    itemField: 'Vật phẩm',
    priceField: 'Giá',
    noHistory: 'Không có lịch sử',
    menuHome: 'Trang chủ',

    notice: 'Thông báo',
    confirm: 'Xác nhận',
    cancel: 'Huỷ',
    congrats: 'Chúc mừng!!!',
    claimMessage: `Bạn sẽ nhận được <span class="highlight"><strong>[xxx]</strong></span><br>sau khi nhấn "Xác nhận"`,
    youReceived: 'Bạn đã nhận được',
    youReceivedMain: 'Bạn đã nhận được vật phẩm chính',
    defaultError: 'Hiện không thể thực hiện, vui lòng thử lại sau',
    unauthorized: 'Bạn chưa đăng nhập',
    account_not_found: 'Tài khoản của bạn chưa đăng nhập vào game',
    region_invalid: 'Khu vực không được hỗ trợ cho sự kiện',
    version_incompatible: 'Sự kiện đã được nâng cấp. Bạn vui lòng tải lại sự kiện',
    item_not_found: 'Không tìm thấy vật phẩm',
    item_invalid: 'Chưa đến thời điểm nhận vật phẩm',
    item_unavailable: 'Chưa đến thời điểm nhận vật phẩm',
    event_unstarted: 'Sự kiện chưa bắt đầu',
    event_stopped: 'Sự kiện đã kết thúc',
    limit_exceeded: 'Bạn đã đạt giới hạn quy đổi vật phẩm',
    packs_purchased: 'Bạn đã mua gói này rồi',
    reroll_limit_exceeded: 'Bạn đã đạt giới hạn làm mới',
    pack_not_found: 'Không có gói',
    discount_not_found: 'Tỉ lệ giảm giá không đúng',
    discount_used: 'Bạn đã sử dụng vé giảm giá này',
    spent_unreached: 'Bạn chưa đạt số kim cương chi tiêu',
    discount_unapplicable: 'Tỉ lệ giảm giá không thể áp dụng'
  },
  en: {
    domain: 'salehunt.ff.garena.vn',
    logoSite: '/images/logo-pk.png',
    saleTag: 'Sale',
    refreshSale: 'Refresh discount',
    buyText: 'Buy',
    boughtText: 'Bought',
    cantBuyText: 'Can not buy',
    guideText: 'Guide text...',
    ticketLabel: 'Sale off ticket',
    confirmBuy: `Do you want to buy this item?<br>Select your discount ticket`,
    warning: 'Bạn chưa chọn vé giảm giá<br>bạn có muốn tiếp tục mua vật phẩm không?',
    rerollConfirm: 'Use [xxx] <img src="/images/icon-diamond.png" class="icon-diamond" alt=""/> to refresh?',
    purchasedError: 'You have already used this discount ticket',
    rerollSuccess: 'Successfully refresh',
    ruleTitle: 'Information',
    rule: '<p>Lorem</p>',
    historyTitle: 'History',
    timeField: 'Time',
    itemField: 'Item',
    priceField: 'Price',
    noHistory: 'No history',
    menuHome: 'Home',

    notice: 'Notice',
    confirm: 'Confirm',
    cancel: 'Cancel',
    congrats: 'Gongratulation!!!',
    claimMessage: `Bạn sẽ nhận được <span class="highlight"><strong>[xxx]</strong></span><br>sau khi nhấn "Xác nhận"`,
    youReceived: 'You received',
    youReceivedMain: 'You received main prize',
    defaultError: 'Error occurred, please try again later',
    unauthorized: 'Please login',
    account_not_found: 'Your account is not activated ingame',
    region_invalid: 'Region is invalid',
    version_incompatible: 'Event is upgraded. Please reload your site',
    item_not_found: 'No item found',
    item_invalid: 'Item is invalid',
    item_unavailable: 'Item is not available yet',
    event_unstarted: 'Event has not started yet',
    event_stopped: 'Event has ended',
    limit_exceeded: 'You have reach the item limitation',
    packs_purchased: 'You have already bought this pack',
    reroll_limit_exceeded: 'You have reach refresh limitation',
    pack_not_found: 'No pack found',
    discount_not_found: 'Discount rate is not exist',
    discount_used: 'Discount have already used',
    spent_unreached: 'You need to spent more to buy this item',
    discount_unapplicable: 'Discount can not be applied'
  }
}